// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VFSModel.proto

package vfs.impl.proto;

final class VFSModel {
  private VFSModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SuperNodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 blockSize = 1;
    boolean hasBlockSize();
    int getBlockSize();
  }
  public static final class SuperNode extends
      com.google.protobuf.GeneratedMessage
      implements SuperNodeOrBuilder {
    // Use SuperNode.newBuilder() to construct.
    private SuperNode(Builder builder) {
      super(builder);
    }
    private SuperNode(boolean noInit) {}
    
    private static final SuperNode defaultInstance;
    public static SuperNode getDefaultInstance() {
      return defaultInstance;
    }
    
    public SuperNode getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vfs.impl.proto.VFSModel.internal_static_vfs_impl_proto_SuperNode_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vfs.impl.proto.VFSModel.internal_static_vfs_impl_proto_SuperNode_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 blockSize = 1;
    public static final int BLOCKSIZE_FIELD_NUMBER = 1;
    private int blockSize_;
    public boolean hasBlockSize() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getBlockSize() {
      return blockSize_;
    }
    
    private void initFields() {
      blockSize_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasBlockSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, blockSize_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, blockSize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static vfs.impl.proto.VFSModel.SuperNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static vfs.impl.proto.VFSModel.SuperNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static vfs.impl.proto.VFSModel.SuperNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static vfs.impl.proto.VFSModel.SuperNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static vfs.impl.proto.VFSModel.SuperNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static vfs.impl.proto.VFSModel.SuperNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static vfs.impl.proto.VFSModel.SuperNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static vfs.impl.proto.VFSModel.SuperNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static vfs.impl.proto.VFSModel.SuperNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static vfs.impl.proto.VFSModel.SuperNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(vfs.impl.proto.VFSModel.SuperNode prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements vfs.impl.proto.VFSModel.SuperNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vfs.impl.proto.VFSModel.internal_static_vfs_impl_proto_SuperNode_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vfs.impl.proto.VFSModel.internal_static_vfs_impl_proto_SuperNode_fieldAccessorTable;
      }
      
      // Construct using vfs.impl.proto.VFSModel.SuperNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        blockSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vfs.impl.proto.VFSModel.SuperNode.getDescriptor();
      }
      
      public vfs.impl.proto.VFSModel.SuperNode getDefaultInstanceForType() {
        return vfs.impl.proto.VFSModel.SuperNode.getDefaultInstance();
      }
      
      public vfs.impl.proto.VFSModel.SuperNode build() {
        vfs.impl.proto.VFSModel.SuperNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private vfs.impl.proto.VFSModel.SuperNode buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        vfs.impl.proto.VFSModel.SuperNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public vfs.impl.proto.VFSModel.SuperNode buildPartial() {
        vfs.impl.proto.VFSModel.SuperNode result = new vfs.impl.proto.VFSModel.SuperNode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.blockSize_ = blockSize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vfs.impl.proto.VFSModel.SuperNode) {
          return mergeFrom((vfs.impl.proto.VFSModel.SuperNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(vfs.impl.proto.VFSModel.SuperNode other) {
        if (other == vfs.impl.proto.VFSModel.SuperNode.getDefaultInstance()) return this;
        if (other.hasBlockSize()) {
          setBlockSize(other.getBlockSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasBlockSize()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              blockSize_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 blockSize = 1;
      private int blockSize_ ;
      public boolean hasBlockSize() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getBlockSize() {
        return blockSize_;
      }
      public Builder setBlockSize(int value) {
        bitField0_ |= 0x00000001;
        blockSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearBlockSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        blockSize_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:vfs.impl.proto.SuperNode)
    }
    
    static {
      defaultInstance = new SuperNode(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:vfs.impl.proto.SuperNode)
  }
  
  public interface DirEntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 inode = 1;
    boolean hasInode();
    int getInode();
    
    // required string name = 2;
    boolean hasName();
    String getName();
  }
  public static final class DirEntry extends
      com.google.protobuf.GeneratedMessage
      implements DirEntryOrBuilder {
    // Use DirEntry.newBuilder() to construct.
    private DirEntry(Builder builder) {
      super(builder);
    }
    private DirEntry(boolean noInit) {}
    
    private static final DirEntry defaultInstance;
    public static DirEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public DirEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vfs.impl.proto.VFSModel.internal_static_vfs_impl_proto_DirEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vfs.impl.proto.VFSModel.internal_static_vfs_impl_proto_DirEntry_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 inode = 1;
    public static final int INODE_FIELD_NUMBER = 1;
    private int inode_;
    public boolean hasInode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getInode() {
      return inode_;
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      inode_ = 0;
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasInode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, inode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, inode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static vfs.impl.proto.VFSModel.DirEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static vfs.impl.proto.VFSModel.DirEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static vfs.impl.proto.VFSModel.DirEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static vfs.impl.proto.VFSModel.DirEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static vfs.impl.proto.VFSModel.DirEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static vfs.impl.proto.VFSModel.DirEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static vfs.impl.proto.VFSModel.DirEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static vfs.impl.proto.VFSModel.DirEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static vfs.impl.proto.VFSModel.DirEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static vfs.impl.proto.VFSModel.DirEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(vfs.impl.proto.VFSModel.DirEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements vfs.impl.proto.VFSModel.DirEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vfs.impl.proto.VFSModel.internal_static_vfs_impl_proto_DirEntry_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vfs.impl.proto.VFSModel.internal_static_vfs_impl_proto_DirEntry_fieldAccessorTable;
      }
      
      // Construct using vfs.impl.proto.VFSModel.DirEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        inode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vfs.impl.proto.VFSModel.DirEntry.getDescriptor();
      }
      
      public vfs.impl.proto.VFSModel.DirEntry getDefaultInstanceForType() {
        return vfs.impl.proto.VFSModel.DirEntry.getDefaultInstance();
      }
      
      public vfs.impl.proto.VFSModel.DirEntry build() {
        vfs.impl.proto.VFSModel.DirEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private vfs.impl.proto.VFSModel.DirEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        vfs.impl.proto.VFSModel.DirEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public vfs.impl.proto.VFSModel.DirEntry buildPartial() {
        vfs.impl.proto.VFSModel.DirEntry result = new vfs.impl.proto.VFSModel.DirEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.inode_ = inode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vfs.impl.proto.VFSModel.DirEntry) {
          return mergeFrom((vfs.impl.proto.VFSModel.DirEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(vfs.impl.proto.VFSModel.DirEntry other) {
        if (other == vfs.impl.proto.VFSModel.DirEntry.getDefaultInstance()) return this;
        if (other.hasInode()) {
          setInode(other.getInode());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasInode()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              inode_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 inode = 1;
      private int inode_ ;
      public boolean hasInode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getInode() {
        return inode_;
      }
      public Builder setInode(int value) {
        bitField0_ |= 0x00000001;
        inode_ = value;
        onChanged();
        return this;
      }
      public Builder clearInode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        inode_ = 0;
        onChanged();
        return this;
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:vfs.impl.proto.DirEntry)
    }
    
    static {
      defaultInstance = new DirEntry(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:vfs.impl.proto.DirEntry)
  }
  
  public interface NodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 no = 1;
    boolean hasNo();
    int getNo();
    
    // required int32 parentNo = 2;
    boolean hasParentNo();
    int getParentNo();
    
    // required string name = 3;
    boolean hasName();
    String getName();
    
    // required int32 flags = 4;
    boolean hasFlags();
    int getFlags();
    
    // required int32 dataBlockNo = 5;
    boolean hasDataBlockNo();
    int getDataBlockNo();
    
    // optional bytes checksum = 6;
    boolean hasChecksum();
    com.google.protobuf.ByteString getChecksum();
    
    // required int64 timestamp = 7;
    boolean hasTimestamp();
    long getTimestamp();
    
    // optional int64 size = 8;
    boolean hasSize();
    long getSize();
  }
  public static final class Node extends
      com.google.protobuf.GeneratedMessage
      implements NodeOrBuilder {
    // Use Node.newBuilder() to construct.
    private Node(Builder builder) {
      super(builder);
    }
    private Node(boolean noInit) {}
    
    private static final Node defaultInstance;
    public static Node getDefaultInstance() {
      return defaultInstance;
    }
    
    public Node getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vfs.impl.proto.VFSModel.internal_static_vfs_impl_proto_Node_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vfs.impl.proto.VFSModel.internal_static_vfs_impl_proto_Node_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 no = 1;
    public static final int NO_FIELD_NUMBER = 1;
    private int no_;
    public boolean hasNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getNo() {
      return no_;
    }
    
    // required int32 parentNo = 2;
    public static final int PARENTNO_FIELD_NUMBER = 2;
    private int parentNo_;
    public boolean hasParentNo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getParentNo() {
      return parentNo_;
    }
    
    // required string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 flags = 4;
    public static final int FLAGS_FIELD_NUMBER = 4;
    private int flags_;
    public boolean hasFlags() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getFlags() {
      return flags_;
    }
    
    // required int32 dataBlockNo = 5;
    public static final int DATABLOCKNO_FIELD_NUMBER = 5;
    private int dataBlockNo_;
    public boolean hasDataBlockNo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getDataBlockNo() {
      return dataBlockNo_;
    }
    
    // optional bytes checksum = 6;
    public static final int CHECKSUM_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString checksum_;
    public boolean hasChecksum() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.google.protobuf.ByteString getChecksum() {
      return checksum_;
    }
    
    // required int64 timestamp = 7;
    public static final int TIMESTAMP_FIELD_NUMBER = 7;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // optional int64 size = 8;
    public static final int SIZE_FIELD_NUMBER = 8;
    private long size_;
    public boolean hasSize() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public long getSize() {
      return size_;
    }
    
    private void initFields() {
      no_ = 0;
      parentNo_ = 0;
      name_ = "";
      flags_ = 0;
      dataBlockNo_ = 0;
      checksum_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
      size_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParentNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFlags()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataBlockNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, no_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, parentNo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, flags_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, dataBlockNo_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, checksum_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, timestamp_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, size_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, no_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, parentNo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, flags_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, dataBlockNo_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, checksum_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, timestamp_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, size_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static vfs.impl.proto.VFSModel.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static vfs.impl.proto.VFSModel.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static vfs.impl.proto.VFSModel.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static vfs.impl.proto.VFSModel.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static vfs.impl.proto.VFSModel.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static vfs.impl.proto.VFSModel.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static vfs.impl.proto.VFSModel.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static vfs.impl.proto.VFSModel.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static vfs.impl.proto.VFSModel.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static vfs.impl.proto.VFSModel.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(vfs.impl.proto.VFSModel.Node prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements vfs.impl.proto.VFSModel.NodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vfs.impl.proto.VFSModel.internal_static_vfs_impl_proto_Node_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vfs.impl.proto.VFSModel.internal_static_vfs_impl_proto_Node_fieldAccessorTable;
      }
      
      // Construct using vfs.impl.proto.VFSModel.Node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        no_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        parentNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        flags_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        dataBlockNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        checksum_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        size_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vfs.impl.proto.VFSModel.Node.getDescriptor();
      }
      
      public vfs.impl.proto.VFSModel.Node getDefaultInstanceForType() {
        return vfs.impl.proto.VFSModel.Node.getDefaultInstance();
      }
      
      public vfs.impl.proto.VFSModel.Node build() {
        vfs.impl.proto.VFSModel.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private vfs.impl.proto.VFSModel.Node buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        vfs.impl.proto.VFSModel.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public vfs.impl.proto.VFSModel.Node buildPartial() {
        vfs.impl.proto.VFSModel.Node result = new vfs.impl.proto.VFSModel.Node(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.no_ = no_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.parentNo_ = parentNo_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.flags_ = flags_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.dataBlockNo_ = dataBlockNo_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.checksum_ = checksum_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.size_ = size_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vfs.impl.proto.VFSModel.Node) {
          return mergeFrom((vfs.impl.proto.VFSModel.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(vfs.impl.proto.VFSModel.Node other) {
        if (other == vfs.impl.proto.VFSModel.Node.getDefaultInstance()) return this;
        if (other.hasNo()) {
          setNo(other.getNo());
        }
        if (other.hasParentNo()) {
          setParentNo(other.getParentNo());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasFlags()) {
          setFlags(other.getFlags());
        }
        if (other.hasDataBlockNo()) {
          setDataBlockNo(other.getDataBlockNo());
        }
        if (other.hasChecksum()) {
          setChecksum(other.getChecksum());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNo()) {
          
          return false;
        }
        if (!hasParentNo()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasFlags()) {
          
          return false;
        }
        if (!hasDataBlockNo()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              no_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              parentNo_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              flags_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              dataBlockNo_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              checksum_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              timestamp_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              size_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 no = 1;
      private int no_ ;
      public boolean hasNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getNo() {
        return no_;
      }
      public Builder setNo(int value) {
        bitField0_ |= 0x00000001;
        no_ = value;
        onChanged();
        return this;
      }
      public Builder clearNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        no_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 parentNo = 2;
      private int parentNo_ ;
      public boolean hasParentNo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getParentNo() {
        return parentNo_;
      }
      public Builder setParentNo(int value) {
        bitField0_ |= 0x00000002;
        parentNo_ = value;
        onChanged();
        return this;
      }
      public Builder clearParentNo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parentNo_ = 0;
        onChanged();
        return this;
      }
      
      // required string name = 3;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
      }
      
      // required int32 flags = 4;
      private int flags_ ;
      public boolean hasFlags() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getFlags() {
        return flags_;
      }
      public Builder setFlags(int value) {
        bitField0_ |= 0x00000008;
        flags_ = value;
        onChanged();
        return this;
      }
      public Builder clearFlags() {
        bitField0_ = (bitField0_ & ~0x00000008);
        flags_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 dataBlockNo = 5;
      private int dataBlockNo_ ;
      public boolean hasDataBlockNo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getDataBlockNo() {
        return dataBlockNo_;
      }
      public Builder setDataBlockNo(int value) {
        bitField0_ |= 0x00000010;
        dataBlockNo_ = value;
        onChanged();
        return this;
      }
      public Builder clearDataBlockNo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dataBlockNo_ = 0;
        onChanged();
        return this;
      }
      
      // optional bytes checksum = 6;
      private com.google.protobuf.ByteString checksum_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasChecksum() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.google.protobuf.ByteString getChecksum() {
        return checksum_;
      }
      public Builder setChecksum(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        checksum_ = value;
        onChanged();
        return this;
      }
      public Builder clearChecksum() {
        bitField0_ = (bitField0_ & ~0x00000020);
        checksum_ = getDefaultInstance().getChecksum();
        onChanged();
        return this;
      }
      
      // required int64 timestamp = 7;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000040;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000040);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 size = 8;
      private long size_ ;
      public boolean hasSize() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public long getSize() {
        return size_;
      }
      public Builder setSize(long value) {
        bitField0_ |= 0x00000080;
        size_ = value;
        onChanged();
        return this;
      }
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000080);
        size_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:vfs.impl.proto.Node)
    }
    
    static {
      defaultInstance = new Node(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:vfs.impl.proto.Node)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_vfs_impl_proto_SuperNode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vfs_impl_proto_SuperNode_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_vfs_impl_proto_DirEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vfs_impl_proto_DirEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_vfs_impl_proto_Node_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vfs_impl_proto_Node_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016VFSModel.proto\022\016vfs.impl.proto\"\036\n\tSupe" +
      "rNode\022\021\n\tblockSize\030\001 \002(\005\"\'\n\010DirEntry\022\r\n\005" +
      "inode\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\"\211\001\n\004Node\022\n\n\002no" +
      "\030\001 \002(\005\022\020\n\010parentNo\030\002 \002(\005\022\014\n\004name\030\003 \002(\t\022\r" +
      "\n\005flags\030\004 \002(\005\022\023\n\013dataBlockNo\030\005 \002(\005\022\020\n\010ch" +
      "ecksum\030\006 \001(\014\022\021\n\ttimestamp\030\007 \002(\003\022\014\n\004size\030" +
      "\010 \001(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_vfs_impl_proto_SuperNode_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_vfs_impl_proto_SuperNode_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_vfs_impl_proto_SuperNode_descriptor,
              new java.lang.String[] { "BlockSize", },
              vfs.impl.proto.VFSModel.SuperNode.class,
              vfs.impl.proto.VFSModel.SuperNode.Builder.class);
          internal_static_vfs_impl_proto_DirEntry_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_vfs_impl_proto_DirEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_vfs_impl_proto_DirEntry_descriptor,
              new java.lang.String[] { "Inode", "Name", },
              vfs.impl.proto.VFSModel.DirEntry.class,
              vfs.impl.proto.VFSModel.DirEntry.Builder.class);
          internal_static_vfs_impl_proto_Node_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_vfs_impl_proto_Node_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_vfs_impl_proto_Node_descriptor,
              new java.lang.String[] { "No", "ParentNo", "Name", "Flags", "DataBlockNo", "Checksum", "Timestamp", "Size", },
              vfs.impl.proto.VFSModel.Node.class,
              vfs.impl.proto.VFSModel.Node.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
